#!/usr/bin/env bash

#scp -r ./src/ growl:/home/lprfenau/poker/src
#scp -r ./run/ growl:/home/lprfenau/poker/run
#scp .python-version growl:/home/lprfenau/poker/
#scp Dockerfile growl:/home/lprfenau/poker/
#scp docker-compose.yml growl:/home/lprfenau/poker/
#scp pyproject.toml growl:/home/lprfenau/poker/
#scp uv.lock growl:/home/lprfenau/poker/

#scp -r ./src/ click1:/home/lprfenau/poker/src
#scp -r ./run/ click1:/home/lprfenau/poker/run
#scp .python-version click1:/home/lprfenau/poker/
#scp Dockerfile click1:/home/lprfenau/poker/
#scp docker-compose.yml click1:/home/lprfenau/poker/
#scp pyproject.toml click1:/home/lprfenau/poker/
#scp uv.lock click1:/home/lprfenau/poker/

rsync -avz -e "ssh -q" ./src ./run ./data bc_pretrained_model*.pt .rayignore .python-version get_from_docker remove_last_X_run_results existing_results Dockerfile docker-compose.yml pyproject.toml uv.lock click1:/home/lprfenau/poker/