import tkinter as tk
import torch
import os
import argparse
import glob
import random

# --- Local Project Imports ---
from src.app.play_vs_ai import HumanAIPokerManager
from src.ppo_self_play.alg import PPO, PPOInferenceWrapper, RNNPPOInferenceWrapper, RNNPPO
from src.app.play_gui import PokerGameGUI
from src.ppo_self_play.global_settings import IS_RECURRENT


def get_latest_run_folder(base_path="results"):
    runs = glob.glob(os.path.join(base_path, "run_*"))
    if not runs:
        raise ValueError(f"No run folders found in {base_path}")
    return max(runs, key=os.path.getmtime)


def load_poker_ai(model_path, device):
    """
    Loads a .pt file generated by trainer_actor.py into a playable AI wrapper,
    accounting for both model weights and optimizer parameters.
    """
    print(f"Loading AI Model from {model_path}...")

    # 1. Initialize the raw networks and wrap them in the Inference Wrapper for gameplay
    if IS_RECURRENT:
        models = RNNPPO.init_networks(device, mode="beta", discrete=False)
        ai_player = RNNPPOInferenceWrapper(models, discrete=False)
    else:
        models = PPO.init_networks(device, mode="beta", discrete=False)
        ai_player = PPOInferenceWrapper(models, discrete=False)

    # 3. Load the full checkpoint saved by the trainer
    checkpoint = torch.load(model_path, map_location=device, weights_only=True)

    # 4. Unpack the weights and optimizer params
    if isinstance(checkpoint, tuple) and len(checkpoint) == 2:
        model_weights, optimizer_params = checkpoint
        print("Successfully unpacked model weights from training checkpoint.")
    else:
        model_weights = checkpoint
        print("Loaded legacy weights-only format.")

    # 5. Apply parameters to the wrapper
    ai_player.load_params(model_weights)
    ai_player.to(device)

    return ai_player


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Play Heads-Up Poker against your AI.")
    parser.add_argument("--model_path", type=str, default=None, help="Direct path to a specific .pt file.")
    parser.add_argument("--run_folder", type=str, default=None,
                        help="Path to a run folder. Will pick a random model from it.")
    args = parser.parse_args()

    device = torch.device("cpu")

    if args.model_path:
        model_path = args.model_path
        print(f"Using explicitly provided model: {model_path}")
    else:
        target_folder = args.run_folder if args.run_folder else get_latest_run_folder()
        players_dir = os.path.join(target_folder, "players")

        if not os.path.exists(players_dir):
            print(f"Error: Could not find players directory at {players_dir}")
            exit(1)

        model_files = glob.glob(os.path.join(players_dir, "*.pt"))
        if not model_files:
            print(f"Error: No .pt files found in {players_dir}")
            exit(1)

        model_path = random.choice(model_files)
        model_id = os.path.splitext(os.path.basename(model_path))[0]
        run_name = os.path.basename(os.path.normpath(target_folder))

        print(f"\n🎲 Selected Run Folder: {run_name}")
        print(f"🎲 Randomly selected Model ID: {model_id}\n")

    if not os.path.exists(model_path):
        print(f"Error: Could not find model at '{model_path}'. Please check the path.")
    else:
        try:
            ai_player = load_poker_ai(model_path, device)
            game_manager = HumanAIPokerManager(ai_player_model=ai_player)
            root = tk.Tk()
            app = PokerGameGUI(root, game_manager)
            root.mainloop()
        except Exception as e:
            print(f"Failed to start the game: {e}")